name: Update Instrument Master

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest Instrument Master JSON
        run: curl -s -o OpenAPIScripMaster.json https://margincalculator.angelone.in/OpenAPI_File/files/OpenAPIScripMaster.json

      - name: Commit and push if changed
        run: |
          git config --global user.name "Auto Updater"
          git config --global user.email "auto-updater@example.com"
          git add OpenAPIScripMaster.json
          git commit -m "Auto-update Instrument Master JSON" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git push



